from pydantic import BaseModel, Field
from typing import Literal

class ContentVariants(BaseModel):
    """Pydantic model for platform-specific content variants."""
    x_post: str = Field(..., description="Content for an X (Twitter) post, max 280 characters.")
    linkedin_post: str = Field(..., description="Content for a LinkedIn post, generally longer and more professional.")

class LLMContent(BaseModel):
    """Pydantic model for the structured output generated by the LLM."""
    title: str = Field(..., description="A compelling title for the content.")
    rationale: str = Field(..., description="Editorial rationale explaining the content's value.")
    category: str = Field(..., description="The category the content belongs to (e.g., 'Technology', 'Marketing').")
    variants: ContentVariants = Field(..., description="Platform-specific content variants.")

class IngestedContent(BaseModel):
    """Pydantic model for content ingested and ready for LLM processing."""
    content_type: Literal["text", "url", "pdf"] = Field(..., description="Type of the ingested content.")
    extracted_content: str = Field(..., description="The full extracted text content.")
    source_identifier: str = Field(..., description="A unique identifier for the source content (e.g., SHA256 hash or URL).")

class ProcessedContent(BaseModel):
    """Pydantic model for fully processed content, including LLM output."""
    user_id: int = Field(..., description="Telegram user ID who initiated the request.")
    submission_timestamp: str = Field(..., description="ISO format timestamp of content submission.")
    content_type: Literal["text", "url", "pdf"] = Field(..., description="Type of the ingested content.")
    source_identifier: str = Field(..., description="A unique identifier for the source content.")
    style_hash: str = Field(..., description="SHA256 hash of the user's style prompt at the time of processing.")
    llm_output: LLMContent = Field(..., description="Structured output from the LLM.")
